[FEATURE] yielding dial object during Dial#dial
adhearsion/adhearsion pull request #623
Opened 2017-10-20 19:07 UTC by gfaza

attn @sfgeorge, @lpradovera

Yielding the newly initialized dial object during `Dial#dial`, primarily so that we can access the dial object later for subsequent calls to `split` and `rejoin`.

2018-07-11 15:17 UTC, sfgeorge commented
@gfaza Apologies for the delay, mate.  Can you rebase this atop the latest develop?

2018-07-11 15:32 UTC, chewi commented
When this was described to me, I thought it would yield somewhere during the call. If this is just used to fish out the Dial instance then wouldn't it be simpler to include it in DialStatus?

2018-07-11 17:35 UTC, gfaza commented
@chewi, I think the main reason for fishing it out like this (i.e., as early as possible), was to make sure we got access to the `dial` object, particularly in scenarios were the `#dial` method might error out, throw an exception, or otherwise get interrupted, prior to reaching the point where it would normally return the `dial.status`.

2018-07-11 18:48 UTC, sfgeorge commented
Ah yes, that's right.  The `dial.await_completion` in #dial means that you are not receiving `dial.status` until the call legs are completely ended.

But by yielding the Dial object from CallController#dial, it allows you to do some pretty cool stuff with the Dial#split object.  Without this, you can't do anything with Dial#split, until the call is already over... rendering #split useless.

A contrived example of playing with Dial#split, when it's yielded while the call is still alive:

```ruby
class MyMainCallController < Adhearsion::CallController
  def run
    dial party_line do |dial_object|
      sleep 1.minute

      if call.alive? && call.active? && dial_obj.try(:status).try(:result).eql? :answer
        # Tell both parties that the time is almost up!  Then dial_obj.merge to allow them to wrap up their convo.
        dial_object.split main: AlmostOuttaTimeCallController,
                          others: AlmostOuttaTimeCallController
      end
    end
  end
end
```

2018-07-11 19:10 UTC, chewi commented
Okay but as you have it now, isn't it going to wait for that block to finish before it even places the calls? I don't think the above example would work. I guess you could do it in a separate thread though.

2018-07-11 20:04 UTC, sfgeorge commented
Very good call, you're right.  Sorry, example was a little _too_ contrived.  Closer to the mark of how we use this:

```ruby
class MyMainCallController < Adhearsion::CallController
  def run
    @dial_object = nil

    set_call_events

    dial 'SIP/party_line' { |dial_obj| @dial_object = dial_obj } 
  end

  def set_call_events
    call.on_joined do |joined|
      sleep 1.minute # Let them talk for 1 minute

      next unless call.alive? && call.active?

      # Tell both parties that the time is almost up! The AlmostOuttaTimeCallController can then merge them once again to allow them to wrap up their convo.
      @dial_object.split main: AlmostOuttaTimeCallController,
                          others: AlmostOuttaTimeCallController
    end
end
```

2018-07-11 20:46 UTC, chewi commented
Yes, that was more how I imagined it.

2018-07-11 20:50 UTC, chewi requested changes

2018-07-11 20:50 UTC, chewi commented on spec/adhearsion/call_controller/dial_spec.rb
> +            sleep 0.1
I suspect this `sleep` will cause problems on Travis as it's not always that fast. I think you should use a latch like the other examples.

2018-08-06 20:43 UTC, gfaza commented
@chewi - please give the spec another look, now that i've implemented use of `latch` rather than `sleep`:  one latch to make sure the thread had enough time to perform the `yield` inside the `#dial`, and one latch to make sure the `#dial` had enough time to terminate.

2018-08-06 20:50 UTC, chewi approved these changes

2018-08-06 20:52 UTC, chewi requested changes
I clicked approve as I thought it looked good but then I noticed that the test failed under Travis. Ping me when it passes.

2018-08-07 16:47 UTC, gfaza commented
@chewi - the spec appears to be passing as of late, please have a look when you get a chance.

2018-08-07 21:38 UTC, chewi approved these changes

2018-08-07 21:40 UTC, merged